language: node_js
node_js:
  - '0.11'
  - '4'
  - '5'
env:
  - NODE_ENV=test
before_script:
  - npm install
script:
  - npm run coveralls
  - ./node_modules/jshint/bin/jshint lib/*.js
  - ./node_modules/jshint/bin/jshint test/*.js
after_failure:
  - ls -1 log
  - cat log/*
